# Generated by Django 5.1 on 2025-05-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morph_auth', '0002_chatlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_history',
        ),
    ]
